objects = Exer02_04.exe \
          Exer02_08.exe \
          Exer02_12.exe \
          Exer02_16.exe \
          Exer02_35.exe \
          Exer02_41_1.exe \
          Exer02_41_2.exe \
          Exer02_41_3.exe \
          Exer02_42_1.exe \
          Exer02_42_2.exe \
          Exer02_42_3.exe \
          Page046_underline.exe \
          Page056_void.exe \
          Page069_auto.exe

all: $(objects)
	cp $(objects) ./obj/

Exer02_04.exe: Exer02_04.cpp
	g++ -std=c++11 -Wall -o Exer02_04.exe Exer02_04.cpp

Exer02_08.exe: Exer02_08.cpp
	g++ -std=c++11 -Wall -o Exer02_08.exe Exer02_08.cpp

Exer02_09.exe: Exer02_09.cpp
	g++ -std=c++11 -Wall -o Exer02_09.exe Exer02_09.cpp

Exer02_12.exe: Exer02_12.cpp
	g++ -std=c++11 -Wall -o Exer02_12.exe Exer02_12.cpp

Exer02_16.exe: Exer02_16.cpp
	g++ -std=c++11 -Wall -o Exer02_16.exe Exer02_16.cpp

Exer02_27.exe: Exer02_27.cpp
	g++ -std=c++11 -Wall -o Exer02_27.exe Exer02_27.cpp	

Exer02_34.exe: Exer02_34.cpp
	g++ -std=c++11 -Wall -o Exer02_34.exe Exer02_34.cpp	

Exer02_35.exe: Exer02_35.cpp
	g++ -std=c++11 -Wall -o Exer02_35.exe Exer02_35.cpp	

Exer02_39.exe: Exer02_39.cpp
	g++ -std=c++11 -Wall -o Exer02_39.exe Exer02_39.cpp	

Exer02_41_1.exe: Exer02_41_1.cpp
	g++ -std=c++11 -Wall -o Exer02_41_1.exe Exer02_41_1.cpp

Exer02_41_2.exe: Exer02_41_2.cpp
	g++ -std=c++11 -Wall -o Exer02_41_2.exe Exer02_41_2.cpp

Exer02_41_3.exe: Exer02_41_3.cpp
	g++ -std=c++11 -Wall -o Exer02_41_3.exe Exer02_41_3.cpp

Exer02_42_1.exe: Exer02_42_1.cpp
	g++ -std=c++11 -Wall -o Exer02_42_1.exe Exer02_42_1.cpp

Exer02_42_2.exe: Exer02_42_2.cpp
	g++ -std=c++11 -Wall -o Exer02_42_2.exe Exer02_42_2.cpp

Exer02_42_3.exe: Exer02_42_3.cpp
	g++ -std=c++11 -Wall -o Exer02_42_3.exe Exer02_42_3.cpp

Page046_underline.exe: Page046_underline.cpp
	g++ -std=c++11 -Wall -o Page046_underline.exe Page046_underline.cpp

Page056_void.exe: Page056_void.cpp
	g++ -std=c++11 -Wall -o Page056_void.exe Page056_void.cpp

Page061_const.exe: Page061_const.cpp
	g++ -std=c++11 -Wall -o Page061_const.exe Page061_const.cpp

Page069_auto.exe: Page069_auto.cpp
	g++ -std=c++11 -Wall -o Page069_auto.exe Page069_auto.cpp

clean:
	rm $(objects)
	rm -f obj/*

